### ISSUE TITLE
3.3 | Remove DSOAL and EAX support :(

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#83]
...alternatively, resolve the issues that led to this point. Some sound-tag issues had been resolved after the inception of this decision. Some other fatal crashes still occur and are attributed to coincidental sound cues.

Part of #44 

Refer to #67 for DSOAL support.

**Comment by SubhadeepJasu** [comment]
May be distribute a custom ini for the settings, so that the sound issues are resolved for everyone?

**Comment by BinToss** [comment]
The default settings in newer build of DSOAL (which are now compatible with Halo again) no longer need tweaks to be better balanced.

However, I still get crashes (rarely) which seem to be linked to gravity grenades. These crashes are extremely difficult to diagnose with the tools we have now, but I'm beginning to think it's a memory access violation and/or a memory pointer overrun (continuing to execute the next function rather than returning).

**Comment by BinToss** [comment]
Additionally one of two other users who've tested the newest DSOAL build with SPV3 had reported "muffled" audio. This may be platform-specific, but it's worth noting.
https://imgur.com/gallery/RBpFuqA

**Comment by BinToss** [comment]
![image](https://user-images.githubusercontent.com/7243190/103188204-5f7b6900-487c-11eb-8792-d66390b156ba.png)
Warning added, but it will open at startup if the EAX setting was left ON. I know why it's happening, but I don't know what I should do instead.
`Checked="EaxChecked"`

```cs 
private void EaxChecked()
{
  MessageBox.Show("warning")
}
```

**Comment by MirisWisdom** [comment]
Resolved in #90.
